обработка ошибок в unary методах, обертки для новых методов
Tinkoff/invest-api-java-sdk pull request #10
Opened 2022-03-16 10:54 UTC by hondasmx

обработка ошибок в unary методах, 
обертки для GetBondCoupons, GetDividendsForeignIssuer, GetBrokerReport
отказ от optional

2022-03-16 18:28 UTC, zlumyo requested changes

2022-03-16 18:28 UTC, zlumyo commented on core/src/main/java/ru/tinkoff/piapi/core/utils/Helpers.java
> +    if ("RESOURCE_EXHAUSTED".equals(exception.getStatus().getCode().name())) {
Для строк вполне подойдёт и `==` вместо `equals`.

2022-03-16 18:28 UTC, zlumyo commented on core/src/main/java/ru/tinkoff/piapi/core/utils/Helpers.java
> +        var json = new File(Helpers.class.getClassLoader().getResource("errors.json").getFile());
При каждом вызове этого метода будет читаться файл, а затем обновляться `Map`. Попробуй вынести считывание файла в static-инициализатор класса.

2022-03-17 04:41 UTC, hondasmx commented on core/src/main/java/ru/tinkoff/piapi/core/utils/Helpers.java
> +        var json = new File(Helpers.class.getClassLoader().getResource("errors.json").getFile());
он будет читаться только если errorsMap.isEmpty()

2022-03-17 08:25 UTC, zlumyo commented on core/src/main/java/ru/tinkoff/piapi/core/utils/Helpers.java
> +        var json = new File(Helpers.class.getClassLoader().getResource("errors.json").getFile());
Сорри, не заметил. Но всё равно имеет смысл вычитать файл в static-инициализаторе, поскольку может что-то пойти не так во время срабатывания первой ошибки. А так мы сразу при запуске всё сделаем.

2022-03-17 09:45 UTC, malyginvv commented on core/src/main/java/ru/tinkoff/piapi/core/utils/Helpers.java
> +      var id = getErrorId(exception);
Предлагаю использовать методы `io.grpc.Status#fromThrowable` и `io.grpc.Status#trailersFromThrowable`, чтобы получить код ошибки и message из заголовков ответа.

2022-03-17 09:46 UTC, malyginvv commented on core/src/main/java/ru/tinkoff/piapi/core/utils/Helpers.java
> +          var statusRuntimeException = (StatusRuntimeException) t;
Предлагаю сделать общую обработку исключений с unaryCall.

2022-03-18 09:38 UTC, Rinchiny approved these changes

2022-03-18 15:19 UTC, zlumyo commented on core/src/main/resources/errors.json
> +    "description": "Входной параметр *from* является обязательным.  Укажите корректный параметр *from*."
Звёздочки тоже лишние. Этот текст же не будет рендерится как Markdown

2022-03-20 11:12 UTC, zlumyo approved these changes

2022-03-22 04:55 UTC, merged